### ISSUE TITLE
DEPRECATION: Accessing jQuery.Event specific properties is deprecated

### ISSUE THREAD

**Issue by poplevente** [heroku/ember-sortable#186] opened 2018-08-27 07:35 UTC
Hi Guys,

using the latest ember version, we get the following deprication warnings: 

"DEPRECATION: Accessing jQuery.Event specific properties is deprecated. Either use the ember-jquery-legacy addon to normalize events to native events, or explicitly opt into jQuery integration using @ember/optional-features. [deprecation id: ember-views.event-dispatcher.jquery-event] See https://emberjs.com/deprecations/v3.x#toc_jquery-event for more details."

is someone working on this?

**Comment by jgwhite** [comment] 2018-08-28 05:45
Thanks for reporting.

> is someone working on this?

Not presently, no. PRs very welcome.

**Comment by KroneckerDeIta** [comment] 2018-10-30 22:15
I had a little look at this and I think if we change the sortable-item.js mixin so that the following lines in both the getY and getX functions:

`let originalEvent = event.originalEvent;`
`let touches = originalEvent && originalEvent.changedTouches;`

are replaced with:

`let nativeEvent = normalizeEvent(event);`
`let touches = nativeEvent && nativeEvent.changedTouches;`

and add the import for normalizeEvent to the top of that mixin:

`import { normalizeEvent } from 'ember-jquery-legacy';`

and add to the package.json file:

`"ember-jquery-legacy": "^1.0.0"`

I think the deprecation warning will go away.

I leave this comment here as I am not 100% sure how to do pull requests yet.

**Comment by poplevente** [comment] 2018-11-09 08:18
Can someone check this and make the changes? would be nice to have it since soon ember will depricate this and we cannot use it anymore

**Comment by jgwhite** [comment] 2018-11-15 14:18
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests.

The plan is to drop jQuery as a dependency altogether. Keep an eye on #179 for updates.

**Comment by aandis** [comment] 2019-01-20 15:40
Hey @jgwhite. Just upgraded to `1.12.4` and still seeing 

> Accessing jQuery.Event specific properties is deprecated. Either use the ember-jquery-legacy addon to normalize events to native events, or explicitly opt into jQuery integration using @ember/optional-features.

Is that expected?

**Comment by knownasilya** [comment] 2019-01-30 20:51
Seeing it as well.

**Comment by tavosansal** [comment] 2019-03-08 18:29
I can confirm this is still a problem ... looks like #179 was never merged and actually the PR was closed...so should this issue be reopened?

**Comment by allinne** [comment] 2019-06-03 18:11
I agree with @tavosansal the issue is still actual. @jgwhite, could you reopen it and take into development?

**Comment by jgwhite** [comment] 2019-06-04 10:22
Can I confirm whether everyone commenting here is seeing these deprecations warnings in tests or in development?

It looks like there are no references to jQuery in the main library code anymore, just in the test helpers.

With that in mind, let’s focus efforts around ridding the existing helpers of jQuery and, even better, modernizing the helpers https://github.com/heroku/ember-sortable/issues/256

**Comment by allinne** [comment] 2019-06-04 10:34
@jgwhite thank you for reopening!
The deprecations point out [here](https://github.com/heroku/ember-sortable/blob/207b5beb022c5370d7621c586234c01bef176dfd/addon/mixins/sortable-item.js#L704-L732). See [Ember Deprecations Docs](https://deprecations.emberjs.com/v3.x/#toc_jquery-event)
Hope it will be helpfull.

**Comment by jgwhite** [comment] 2019-06-04 10:40
Thanks for the reference to the deprecation guide. Please if anyone has the time to work on removing jQuery from the test helpers then go ahead and open a PR. I’ll be ready and waiting to review it!

**Closed** 2019-06-11 08:11 UTC
